package de.leon_lp9.challengePlugin.management;

import lombok.Getter;

@Getter
public enum Flags{
    Afghanistan("Afghanistan", "https://flagcdn.com/w160/af.png"),
    Agypten("Ägypten", "https://flagcdn.com/w160/eg.png"),
    Aland("Aland", "https://flagcdn.com/w160/ax.png"),
    Albanien("Albanien", "https://flagcdn.com/w160/al.png"),
    Algerien("Algerien", "https://flagcdn.com/w160/dz.png"),
    AmerikanischSamoa("Amerikanisch-Samoa", "https://flagcdn.com/w160/as.png"),
    AmerikanischeJungferninseln("Amerikanische Jungferninseln", "https://flagcdn.com/w160/vi.png"),
    Andorra("Andorra", "https://flagcdn.com/w160/ad.png"),
    Angola("Angola", "https://flagcdn.com/w160/ao.png"),
    Anguilla("Anguilla", "https://flagcdn.com/w160/ai.png"),
    Antarktis("Antarktis", "https://flagcdn.com/w160/aq.png"),
    AntiguaUndBarbuda("Antigua und Barbuda", "https://flagcdn.com/w160/ag.png"),
    Aquatorialguinea("Äquatorialguinea", "https://flagcdn.com/w160/gq.png"),
    Argentinien("Argentinien", "https://flagcdn.com/w160/ar.png"),
    Armenien("Armenien", "https://flagcdn.com/w160/am.png"),
    Aruba("Aruba", "https://flagcdn.com/w160/aw.png"),
    Aserbaidschan("Aserbaidschan", "https://flagcdn.com/w160/az.png"),
    Athiopien("Äthiopien", "https://flagcdn.com/w160/et.png"),
    Australien("Australien", "https://flagcdn.com/w160/au.png"),
    Bahamas("Bahamas", "https://flagcdn.com/w160/bs.png"),
    Bahrain("Bahrain", "https://flagcdn.com/w160/bh.png"),
    Bangladesch("Bangladesch", "https://flagcdn.com/w160/bd.png"),
    Barbados("Barbados", "https://flagcdn.com/w160/bb.png"),
    Belgien("Belgien", "https://flagcdn.com/w160/be.png"),
    Belize("Belize", "https://flagcdn.com/w160/bz.png"),
    Benin("Benin", "https://flagcdn.com/w160/bj.png"),
    Bermuda("Bermuda", "https://flagcdn.com/w160/bm.png"),
    Bhutan("Bhutan", "https://flagcdn.com/w160/bt.png"),
    Bolivien("Bolivien", "https://flagcdn.com/w160/bo.png"),
    BosnienUndHerzegowina("Bosnien und Herzegowina", "https://flagcdn.com/w160/ba.png"),
    Botswana("Botswana", "https://flagcdn.com/w160/bw.png"),
    Bouvetinsel("Bouvetinsel", "https://flagcdn.com/w160/bv.png"),
    Brasilien("Brasilien", "https://flagcdn.com/w160/br.png"),
    BritischeJungferninseln("Britische Jungferninseln", "https://flagcdn.com/w160/vg.png"),
    BritischesTerritoriumImIndischenOzean("Britisches Territorium im Indischen Ozean", "https://flagcdn.com/w160/io.png"),
    Brunei("Brunei", "https://flagcdn.com/w160/bn.png"),
    Bulgarien("Bulgarien", "https://flagcdn.com/w160/bg.png"),
    BurkinaFaso("Burkina Faso", "https://flagcdn.com/w160/bf.png"),
    Burundi("Burundi", "https://flagcdn.com/w160/bi.png"),
    Chile("Chile", "https://flagcdn.com/w160/cl.png"),
    China("China", "https://flagcdn.com/w160/cn.png"),
    Cookinseln("Cookinseln", "https://flagcdn.com/w160/ck.png"),
    CostaRica("Costa Rica", "https://flagcdn.com/w160/cr.png"),
    Curacao("Curacao", "https://flagcdn.com/w160/cw.png"),
    Danemark("Dänemark", "https://flagcdn.com/w160/dk.png"),
    Deutschland("Deutschland", "https://flagcdn.com/w160/de.png"),
    Dominica("Dominica", "https://flagcdn.com/w160/dm.png"),
    DominikanischeRepublik("Dominikanische Republik", "https://flagcdn.com/w160/do.png"),
    Dschibuti("Dschibuti", "https://flagcdn.com/w160/dj.png"),
    Ecuador("Ecuador", "https://flagcdn.com/w160/ec.png"),
    ElSalvador("El Salvador", "https://flagcdn.com/w160/sv.png"),
    Elfenbeinkuste("Elfenbeinküste", "https://flagcdn.com/w160/ci.png"),
    England("England", "https://flagcdn.com/w160/gb-eng.png"),
    Eritrea("Eritrea", "https://flagcdn.com/w160/er.png"),
    Estland("Estland", "https://flagcdn.com/w160/ee.png"),
    Falklandinseln("Falklandinseln", "https://flagcdn.com/w160/fk.png"),
    FaeroeerInseln("Färöer-Inseln", "https://flagcdn.com/w160/fo.png"),
    Fidschi("Fidschi", "https://flagcdn.com/w160/fj.png"),
    Finnland("Finnland", "https://flagcdn.com/w160/fi.png"),
    Frankreich("Frankreich", "https://flagcdn.com/w160/fr.png"),
    FranzosischGuyana("Französisch-Guyana", "https://flagcdn.com/w160/gf.png"),
    FranzosischPolynesien("Französisch-Polynesien", "https://flagcdn.com/w160/pf.png"),
    FranzosischeSudUndAntarktisgebiete("Französische Süd- und Antarktisgebiete", "https://flagcdn.com/w160/tf.png"),
    Gabun("Gabun", "https://flagcdn.com/w160/ga.png"),
    Gambia("Gambia", "https://flagcdn.com/w160/gm.png"),
    Georgien("Georgien", "https://flagcdn.com/w160/ge.png"),
    Ghana("Ghana", "https://flagcdn.com/w160/gh.png"),
    Gibraltar("Gibraltar", "https://flagcdn.com/w160/gi.png"),
    Grenada("Grenada", "https://flagcdn.com/w160/gd.png"),
    Griechenland("Griechenland", "https://flagcdn.com/w160/gr.png"),
    Gronland("Grönland", "https://flagcdn.com/w160/gl.png"),
    Guadeloupe("Guadeloupe", "https://flagcdn.com/w160/gp.png"),
    Guam("Guam", "https://flagcdn.com/w160/gu.png"),
    Guatemala("Guatemala", "https://flagcdn.com/w160/gt.png"),
    Guernsey("Guernsey", "https://flagcdn.com/w160/gg.png"),
    Guinea("Guinea", "https://flagcdn.com/w160/gn.png"),
    GuineaBissau("Guinea-Bissau", "https://flagcdn.com/w160/gw.png"),
    Guyana("Guyana", "https://flagcdn.com/w160/gy.png"),
    Haiti("Haiti", "https://flagcdn.com/w160/ht.png"),
    HeardUndMcDonaldinseln("Heard und McDonaldinseln", "https://flagcdn.com/w160/hm.png"),
    Honduras("Honduras", "https://flagcdn.com/w160/hn.png"),
    Hongkong("Hongkong", "https://flagcdn.com/w160/hk.png"),
    Indien("Indien", "https://flagcdn.com/w160/in.png"),
    Indonesien("Indonesien", "https://flagcdn.com/w160/id.png"),
    InselMan("Insel Man", "https://flagcdn.com/w160/im.png"),
    Irak("Irak", "https://flagcdn.com/w160/iq.png"),
    Iran("Iran", "https://flagcdn.com/w160/ir.png"),
    Irland("Irland", "https://flagcdn.com/w160/ie.png"),
    Island("Island", "https://flagcdn.com/w160/is.png"),
    Israel("Israel", "https://flagcdn.com/w160/il.png"),
    Italien("Italien", "https://flagcdn.com/w160/it.png"),
    Jamaika("Jamaika", "https://flagcdn.com/w160/jm.png"),
    Japan("Japan", "https://flagcdn.com/w160/jp.png"),
    Jemen("Jemen", "https://flagcdn.com/w160/ye.png"),
    Jersey("Jersey", "https://flagcdn.com/w160/je.png"),
    Jordanien("Jordanien", "https://flagcdn.com/w160/jo.png"),
    Kaimaninseln("Kaimaninseln", "https://flagcdn.com/w160/ky.png"),
    Kambodscha("Kambodscha", "https://flagcdn.com/w160/kh.png"),
    Kamerun("Kamerun", "https://flagcdn.com/w160/cm.png"),
    Kanada("Kanada", "https://flagcdn.com/w160/ca.png"),
    KapVerde("Kap Verde", "https://flagcdn.com/w160/cv.png"),
    KaribischeNiederlande("Karibische Niederlande", "https://flagcdn.com/w160/bq.png"),
    Kasachstan("Kasachstan", "https://flagcdn.com/w160/kz.png"),
    Katar("Katar", "https://flagcdn.com/w160/qa.png"),
    Kenia("Kenia", "https://flagcdn.com/w160/ke.png"),
    Kirgisistan("Kirgisistan", "https://flagcdn.com/w160/kg.png"),
    Kiribati("Kiribati", "https://flagcdn.com/w160/ki.png"),
    KleinerenInselbesitzungenDerVereinigtenStaaten("Kleinere nördliche Inselbesitzungen der Vereinigten Staaten", "https://flagcdn.com/w160/um.png"),
    Kokosinseln("Kokosinseln", "https://flagcdn.com/w160/cc.png"),
    Kolumbien("Kolumbien", "https://flagcdn.com/w160/co.png"),
    Komoren("Komoren", "https://flagcdn.com/w160/km.png"),
    Kongo("Kongo", "https://flagcdn.com/w160/cg.png"),
    DemokratischeRepublikKongo("Demokratische Republik Kongo", "https://flagcdn.com/w160/cd.png"),
    Kosovo("Kosovo", "https://flagcdn.com/w160/xk.png"),
    Kroatien("Kroatien", "https://flagcdn.com/w160/hr.png"),
    Kuba("Kuba", "https://flagcdn.com/w160/cu.png"),
    Kuwait("Kuwait", "https://flagcdn.com/w160/kw.png"),
    Laos("Laos", "https://flagcdn.com/w160/la.png"),
    Lesotho("Lesotho", "https://flagcdn.com/w160/ls.png"),
    Lettland("Lettland", "https://flagcdn.com/w160/lv.png"),
    Libanon("Libanon", "https://flagcdn.com/w160/lb.png"),
    Liberia("Liberia", "https://flagcdn.com/w160/lr.png"),
    Libyen("Libyen", "https://flagcdn.com/w160/ly.png"),
    Liechtenstein("Liechtenstein", "https://flagcdn.com/w160/li.png"),
    Litauen("Litauen", "https://flagcdn.com/w160/lt.png"),
    Luxemburg("Luxemburg", "https://flagcdn.com/w160/lu.png"),
    Macao("Macao", "https://flagcdn.com/w160/mo.png"),
    Madagaskar("Madagaskar", "https://flagcdn.com/w160/mg.png"),
    Malawi("Malawi", "https://flagcdn.com/w160/mw.png"),
    Malaysia("Malaysia", "https://flagcdn.com/w160/my.png"),
    Malediven("Malediven", "https://flagcdn.com/w160/mv.png"),
    Mali("Mali", "https://flagcdn.com/w160/ml.png"),
    Malta("Malta", "https://flagcdn.com/w160/mt.png"),
    Marokko("Marokko", "https://flagcdn.com/w160/ma.png"),
    Marshallinseln("Marshallinseln", "https://flagcdn.com/w160/mh.png"),
    Martinique("Martinique", "https://flagcdn.com/w160/mq.png"),
    Mauretanien("Mauretanien", "https://flagcdn.com/w160/mr.png"),
    Mauritius("Mauritius", "https://flagcdn.com/w160/mu.png"),
    Mayotte("Mayotte", "https://flagcdn.com/w160/yt.png"),
    Mexiko("Mexiko", "https://flagcdn.com/w160/mx.png"),
    Mikronesien("Mikronesien", "https://flagcdn.com/w160/fm.png"),
    Moldawien("Moldawien", "https://flagcdn.com/w160/md.png"),
    Monaco("Monaco", "https://flagcdn.com/w160/mc.png"),
    Mongolei("Mongolei", "https://flagcdn.com/w160/mn.png"),
    Montenegro("Montenegro", "https://flagcdn.com/w160/me.png"),
    Montserrat("Montserrat", "https://flagcdn.com/w160/ms.png"),
    Mosambik("Mosambik", "https://flagcdn.com/w160/mz.png"),
    Myanmar("Myanmar", "https://flagcdn.com/w160/mm.png"),
    Namibia("Namibia", "https://flagcdn.com/w160/na.png"),
    Nauru("Nauru", "https://flagcdn.com/w160/nr.png"),
    Nepal("Nepal", "https://flagcdn.com/w160/np.png"),
    Neukaledonien("Neukaledonien", "https://flagcdn.com/w160/nc.png"),
    Neuseeland("Neuseeland", "https://flagcdn.com/w160/nz.png"),
    Nicaragua("Nicaragua", "https://flagcdn.com/w160/ni.png"),
    Niederlande("Niederlande", "https://flagcdn.com/w160/nl.png"),
    Niger("Niger", "https://flagcdn.com/w160/ne.png"),
    Nigeria("Nigeria", "https://flagcdn.com/w160/ng.png"),
    Niue("Niue", "https://flagcdn.com/w160/nu.png"),
    Nordirland("Nordirland", "https://flagcdn.com/w160/gb-nir.png"),
    Nordkorea("Nordkorea", "https://flagcdn.com/w160/kp.png"),
    NordlicheMarianen("Nördliche Marianen", "https://flagcdn.com/w160/mp.png"),
    Nordmazedonien("Nordmazedonien", "https://flagcdn.com/w160/mk.png"),
    Norfolkinsel("Norfolkinsel", "https://flagcdn.com/w160/nf.png"),
    Norwegen("Norwegen", "https://flagcdn.com/w160/no.png"),
    Oman("Oman", "https://flagcdn.com/w160/om.png"),
    Osterreich("Österreich", "https://flagcdn.com/w160/at.png"),
    Osttimor("Osttimor", "https://flagcdn.com/w160/tl.png"),
    Pakistan("Pakistan", "https://flagcdn.com/w160/pk.png"),
    Palastina("Palästina", "https://flagcdn.com/w160/ps.png"),
    Palau("Palau", "https://flagcdn.com/w160/pw.png"),
    Panama("Panama", "https://flagcdn.com/w160/pa.png"),
    PapuaNeuguinea("Papua-Neuguinea", "https://flagcdn.com/w160/pg.png"),
    Paraguay("Paraguay", "https://flagcdn.com/w160/py.png"),
    Peru("Peru", "https://flagcdn.com/w160/pe.png"),
    Philippinen("Philippinen", "https://flagcdn.com/w160/ph.png"),
    Pitcairninseln("Pitcairninseln", "https://flagcdn.com/w160/pn.png"),
    Polen("Polen", "https://flagcdn.com/w160/pl.png"),
    Portugal("Portugal", "https://flagcdn.com/w160/pt.png"),
    PuertoRico("Puerto Rico", "https://flagcdn.com/w160/pr.png"),
    Reunion("Réunion", "https://flagcdn.com/w160/re.png"),
    Ruanda("Ruanda", "https://flagcdn.com/w160/rw.png"),
    Rumanien("Rumänien", "https://flagcdn.com/w160/ro.png"),
    Russland("Russland", "https://flagcdn.com/w160/ru.png"),
    SaintBarthelemy("Saint-Barthélemy", "https://flagcdn.com/w160/bl.png"),
    SaintMartin("Saint-Martin", "https://flagcdn.com/w160/mf.png"),
    Salomonen("Salomonen", "https://flagcdn.com/w160/sb.png"),
    Sambia("Sambia", "https://flagcdn.com/w160/zm.png"),
    Samoa("Samoa", "https://flagcdn.com/w160/ws.png"),
    SanMarino("San Marino", "https://flagcdn.com/w160/sm.png"),
    SaoTomeUndPrincipe("São Tomé und Príncipe", "https://flagcdn.com/w160/st.png"),
    SaudiArabien("Saudi-Arabien", "https://flagcdn.com/w160/sa.png"),
    Schottland("Schottland", "https://flagcdn.com/w160/gb-sct.png"),
    Schweden("Schweden", "https://flagcdn.com/w160/se.png"),
    Schweiz("Schweiz", "https://flagcdn.com/w160/ch.png"),
    Senegal("Senegal", "https://flagcdn.com/w160/sn.png"),
    Serbien("Serbien", "https://flagcdn.com/w160/rs.png"),
    Seychellen("Seychellen", "https://flagcdn.com/w160/sc.png"),
    SierraLeone("Sierra Leone", "https://flagcdn.com/w160/sl.png"),
    Simbabwe("Simbabwe", "https://flagcdn.com/w160/zw.png"),
    Singapur("Singapur", "https://flagcdn.com/w160/sg.png"),
    SintMaarten("Sint Maarten", "https://flagcdn.com/w160/sx.png"),
    Slowakei("Slowakei", "https://flagcdn.com/w160/sk.png"),
    Slowenien("Slowenien", "https://flagcdn.com/w160/si.png"),
    Somalia("Somalia", "https://flagcdn.com/w160/so.png"),
    Spanien("Spanien", "https://flagcdn.com/w160/es.png"),
    SpitzbergenUndJanMayen("Spitzbergen und Jan Mayen", "https://flagcdn.com/w160/sj.png"),
    SriLanka("Sri Lanka", "https://flagcdn.com/w160/lk.png"),
    StHelenaAscensionUndTristanDaCunha("St. Helena, Ascension und Tristan da Cunha", "https://flagcdn.com/w160/sh.png"),
    StKittsUndNevis("St. Kitts und Nevis", "https://flagcdn.com/w160/kn.png"),
    StLucia("St. Lucia", "https://flagcdn.com/w160/lc.png"),
    StPierreUndMiquelon("St. Pierre und Miquelon", "https://flagcdn.com/w160/pm.png"),
    StVincentUndDieGrenadinen("St. Vincent und die Grenadinen", "https://flagcdn.com/w160/vc.png"),
    Sudafrika("Südafrika", "https://flagcdn.com/w160/za.png"),
    Sudan("Sudan", "https://flagcdn.com/w160/sd.png"),
    SudgeorgienUndDieSudlichenSandwichinseln("Südgeorgien und die Südlichen Sandwichinseln", "https://flagcdn.com/w160/gs.png"),
    Sudkorea("Südkorea", "https://flagcdn.com/w160/kr.png"),
    Sudsudan("Südsudan", "https://flagcdn.com/w160/ss.png"),
    Suriname("Suriname", "https://flagcdn.com/w160/sr.png"),
    Swasiland("Swasiland", "https://flagcdn.com/w160/sz.png"),
    Syrien("Syrien", "https://flagcdn.com/w160/sy.png"),
    Tadschikistan("Tadschikistan", "https://flagcdn.com/w160/tj.png"),
    Taiwan("Taiwan", "https://flagcdn.com/w160/tw.png"),
    Tansania("Tansania", "https://flagcdn.com/w160/tz.png"),
    Thailand("Thailand", "https://flagcdn.com/w160/th.png"),
    Togo("Togo", "https://flagcdn.com/w160/tg.png"),
    Tokelau("Tokelau", "https://flagcdn.com/w160/tk.png"),
    Tonga("Tonga", "https://flagcdn.com/w160/to.png"),
    TrinidadUndTobago("Trinidad und Tobago", "https://flagcdn.com/w160/tt.png"),
    Tschad("Tschad", "https://flagcdn.com/w160/td.png"),
    Tschechien("Tschechien", "https://flagcdn.com/w160/cz.png"),
    Tunesien("Tunesien", "https://flagcdn.com/w160/tn.png"),
    Turkei("Türkei", "https://flagcdn.com/w160/tr.png"),
    Turkmenistan("Turkmenistan", "https://flagcdn.com/w160/tm.png"),
    TurksUndCaicosinseln("Turks- und Caicosinseln", "https://flagcdn.com/w160/tc.png"),
    Tuvalu("Tuvalu", "https://flagcdn.com/w160/tv.png"),
    Uganda("Uganda", "https://flagcdn.com/w160/ug.png"),
    Ukraine("Ukraine", "https://flagcdn.com/w160/ua.png"),
    Ungarn("Ungarn", "https://flagcdn.com/w160/hu.png"),
    Uruguay("Uruguay", "https://flagcdn.com/w160/uy.png"),
    Usbekistan("Usbekistan", "https://flagcdn.com/w160/uz.png"),
    Vanuatu("Vanuatu", "https://flagcdn.com/w160/vu.png"),
    Vatikanstadt("Vatikanstadt", "https://flagcdn.com/w160/va.png"),
    Venezuela("Venezuela", "https://flagcdn.com/w160/ve.png"),
    VereinigteArabischeEmirate("Vereinigte Arabische Emirate", "https://flagcdn.com/w160/ae.png"),
    VereinigteStaaten("Vereinigte Staaten", "https://flagcdn.com/w160/us.png"),
    VereinigtesKonigreich("Vereinigtes Königreich", "https://flagcdn.com/w160/gb.png"),
    Vietnam("Vietnam", "https://flagcdn.com/w160/vn.png"),
    Wales("Wales", "https://flagcdn.com/w160/gb-wls.png"),
    WallisUndFutuna("Wallis und Futuna", "https://flagcdn.com/w160/wf.png"),
    Weihnachtsinsel("Weihnachtsinsel", "https://flagcdn.com/w160/cx.png"),
    Weissrussland("Weißrussland", "https://flagcdn.com/w160/by.png"),
    Westsahara("Westsahara", "https://flagcdn.com/w160/eh.png"),
    ZentralafrikanischeRepublik("Zentralafrikanische Republik", "https://flagcdn.com/w160/cf.png"),
    Zypern("Zypern", "https://flagcdn.com/w160/cy.png");

    private final String name;
    private final String url;

    Flags(String name, String url) {
        this.name = name;
        this.url = url;
    }

    public static Flags getRand() {
        return values()[(int) (Math.random() * values().length)];
    }

}
